name: ecommerce
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^13.2.0
  flutter_svg: ^2.1.0
  google_fonts: ^6.2.1
  dio: ^5.8.0+1
  http: ^1.1.0
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.4
  get_it: ^7.6.7
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.8

flutter:

   uses-material-design: true

   assets:
    - assets/images/
  