// Mocks generated by Mockito 5.4.6 from annotations
// in ecommerce/test/bloc/wishlist_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:ecommerce/domain/entities/product.dart' as _i4;
import 'package:ecommerce/domain/repositories/wishlist_repository.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [WishlistRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWishlistRepository extends _i1.Mock
    implements _i2.WishlistRepository {
  MockWishlistRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.ProductEntity>> getWishlist() => (super.noSuchMethod(
        Invocation.method(
          #getWishlist,
          [],
        ),
        returnValue:
            _i3.Future<List<_i4.ProductEntity>>.value(<_i4.ProductEntity>[]),
      ) as _i3.Future<List<_i4.ProductEntity>>);

  @override
  _i3.Future<void> addToWishlist(_i4.ProductEntity? product) =>
      (super.noSuchMethod(
        Invocation.method(
          #addToWishlist,
          [product],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> removeFromWishlist(int? productId) => (super.noSuchMethod(
        Invocation.method(
          #removeFromWishlist,
          [productId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<bool> isInWishlist(int? productId) => (super.noSuchMethod(
        Invocation.method(
          #isInWishlist,
          [productId],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}
